// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujuosfmraatlpnysvyll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqdW9zZm1yYWF0bHBueXN2eWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MzMyODQsImV4cCI6MjA2MjAwOTI4NH0.5Cp2xgZDecBoTVg5v-NXUsqFzDQrgJqnYIKCYu0EPus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);